- name: Install Agent Puppet Debia
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Agent Puppet Debia
  yum:
    name: puppet-agent
    state: present
  when: ansible_os_family == 'RedHat'


- name: Start Puppet-Agent
  service: 
    name: puppet
    state: started
    enabled: yes
