---
#Playbook de teste
- name: Playbook Alex
  hosts: all
  tasks: 
    - name: install webserver in Ubuntu machines
      apt: 
        name: apache2
        state: absent
      when: ansible_os_family == 'Debian'

    - name: install webserver in CentOs  machines
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == 'RedHat'

#    - name: Copy index.html to docker
#      copy:
#        src: index.html
#        dest: /var/www/html/

#    - name: Restart Webserver
#      service:
#        name: httpd
#        state: restarted
#      when: ansible_os_family == 'RedHat'
